config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :products

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root "store#index", as: 'store_index'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_cart.html.erb
<% if cart and not cart.line_items.empty? %>
  <div id="cart" class="bg-white rounded p-2">
    <%= render cart %>
  </div>
<% else %>
  <div id="cart"></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pragprog Books Online Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="bg-green-700">
      <aside data-controller="locale">
        <%= form_tag store_index_path, class: 'locale', method: :get do %>
          <%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), onchange: 'this.form.submit()' %>
          <%= submit_tag 'submit', data: {'locale-target' => 'submit'} %>
        <% end %>
      </aside>
      <%= image_tag 'logo.svg', alt: 'The Pragmatic Bookshelf' %>
      <h1><%= @page_title %></h1>
    </header>

    <section class="flex">
      <nav class="bg-green-900 p-6">
        <%= render partial: 'layouts/cart', locals: { cart: @cart } %>
        <ul class="text-gray-300 leading-8">
          <li><a href="/"><%= t('.home') %></a></li>
          <li><a href="/questions"><%= t('.questions') %></a></li>
          <li><a href="/news"><%= t('.news') %></a></li>
          <li><a href="/contact"><%= t('.contact') %></a></li>
        </ul>

        <% if session[:user_id] %>
          <hr class="my-2">

          <ul class="text-gray-300 leading-8">
            <li><%= link_to "Orders", orders_path %></li>
            <li><%= link_to "Products", products_path %></li>
            <li><%= link_to "Users", users_path %></li>
            <li><%= link_to "Logout", logout_path, method: :delete %></li>
          </ul>
        <% end %>
      </nav>

      <main class="container mx-auto mt-4 px-5 flex">
        <%= yield %>
      </main>
    </section>
  </body>
</html>